spring.application.name=demo
# 1. SQL Server Connection Settings
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=coffee_shop;encrypt=true;trustServerCertificate=true
spring.datasource.username=ps47937
spring.datasource.password=mynewpass123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 2. JPA / Hibernate Behavior
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update

# Shows the SQL queries in the IntelliJ console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false